/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import Modelo.conectorBD;
import Modelo.util;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Aldair
 */
public class Inicio extends javax.swing.JFrame {
Icon modificarImagen;



    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.jtfUser.requestFocus(true);
        this.getRootPane().setDefaultButton(jBIniciosesion);
        this.setLocationRelativeTo(null);
        modificarImagen= new ImageIcon("src/img/bienvenida.png");
        
        jBIniciosesion.setToolTipText("Iniciar Nueva Sesion");
        btsalir.setToolTipText("Salir");
                  
    }
    
    @Override
    //cambiar el icono de la tasita de café
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/printlogo.png"));
        return retValue;
    }
    
    //código para iniciar sesión
    public void iniciarSesion(){
        //final String usuario="aldair", contraseña="12345";
        String user=jtfUser.getText().trim();
        String password=jPassword.getText().trim();
        
        try{
            if(user.length()>0 && password.length()>0){
                //si el usuario valido correctamente los campos
                acceder();
                /*if(usuario.equals(user) && contraseña.equals(password)){
                    JOptionPane.showMessageDialog(null,"BIENVENIDO: "+jtfUser.getText(),"Mensaje",JOptionPane.WARNING_MESSAGE,modificarImagen);
                   menu menu1= new menu();
                   menu1.setVisible(true);
                    dispose();
                }else{
                   JOptionPane.showMessageDialog(null, "Usuario Y/O Contraseña Icorrectas","Mensaje",JOptionPane.WARNING_MESSAGE);
                   jtfUser.setText(""); 
                   jPassword.setText("");
                   jtfUser.requestFocus();
                }*/
            }else{
             JOptionPane.showMessageDialog(null, "Debe Escribir su Usuario Y/O Contraseña","Mensje",JOptionPane.WARNING_MESSAGE);
                jtfUser.requestFocusInWindow();
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void actionPerformed(ActionEvent e) {  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btsalir = new javax.swing.JButton();
        jLabelusuario = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelPassaword = new javax.swing.JLabel();
        jtfUser = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jBIniciosesion = new javax.swing.JButton();
        jLabelfondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btsalir.setBackground(new java.awt.Color(0, 0, 51));
        btsalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btsalir.setForeground(new java.awt.Color(255, 255, 255));
        btsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, 30));

        jLabelusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        getContentPane().add(jLabelusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 260));

        jLabelNombre.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Usuario:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, 20));

        jLabelPassaword.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelPassaword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassaword.setText("Password:");
        getContentPane().add(jLabelPassaword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jtfUser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(jtfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 180, 30));

        jPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 180, 30));

        jBIniciosesion.setBackground(new java.awt.Color(0, 0, 102));
        jBIniciosesion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBIniciosesion.setForeground(new java.awt.Color(255, 255, 255));
        jBIniciosesion.setText("Entrar");
        jBIniciosesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIniciosesionActionPerformed(evt);
            }
        });
        getContentPane().add(jBIniciosesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 308, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_btsalirActionPerformed

    private void jBIniciosesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIniciosesionActionPerformed
        iniciarSesion();
    }//GEN-LAST:event_jBIniciosesionActionPerformed

    private void jPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           jBIniciosesion.requestFocus();
           iniciarSesion();
        }
    }//GEN-LAST:event_jPasswordKeyPressed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btsalir;
    private javax.swing.JButton jBIniciosesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPassaword;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JLabel jLabelusuario;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jtfUser;
    // End of variables declaration//GEN-END:variables
//metodo para colocar el evento de entrar con el boton enter
conectorBD conector=new conectorBD();
String consultaSQL;
String nombre;
String apellido;
String usuario;
String contraseña;
String tipousuario;
String cedula;

public void obtenerDatosGUI(){
    usuario=jtfUser.getText().toUpperCase().trim();
    contraseña=jPassword.getText().trim();
}
public boolean acceder(){
    boolean estado=false;
    obtenerDatosGUI();
    try{
        if(conector.conectar()){
            consultaSQL="CALL sp_iniciar_sesion("+"'"+usuario+"'"+","
                                                 +"'"+contraseña+"'"+");";
            ResultSet resultado=conector.seleccionar(consultaSQL);
            if(resultado.next()){
                nombre=resultado.getString(1);
                apellido=resultado.getString(2);
                usuario=resultado.getString(3);
                contraseña=resultado.getString(4);
                tipousuario=resultado.getString(5);
                cedula=resultado.getString(6);
                JOptionPane.showMessageDialog(null,"BIENVENIDO: "+nombre+" "+apellido,"Mensaje",JOptionPane.WARNING_MESSAGE,modificarImagen);
                menu menu1= new menu();
                menu1.setVisible(true);
                menu1.txtUsuario.setText(usuario);
                menu1.txtoculto.setText(cedula);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Usuario Y/O Contraseña Icorrectas","Mensaje",JOptionPane.WARNING_MESSAGE);
                jtfUser.setText(""); 
                jPassword.setText("");
                jtfUser.requestFocus();
            }
            conector.desconectar();
        }else{
            util.advertir(null,"Error!.. Verifique La Conexion De Base De Datos", null); 
        }
    }catch (SQLException sqle){
      System.out.println("Error.."+sqle.getMessage());
    }
    return estado;
}

}
