/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.ComboMedicamento;
import Controlador.FullSelectorListener;
import Modelo.OperacionesInventarioInicial;
import java.util.Date;
import javax.swing.JTextField;

/**
 *
 * @author Aldair
 */
public class InventarioInicial extends javax.swing.JInternalFrame {

    /**
     * Creates new form InventarioInicial
     */
    public InventarioInicial() {
        initComponents();
        OperacionesInventarioInicial operacion=new OperacionesInventarioInicial();
        operacion.obtenerMedicamentos(comboProductos);
        
        DateFechaEntrada.setDate(new Date());
        //Centrar letras
        txtBuscador.setHorizontalAlignment(JTextField.CENTER);
        txtCantidadCompra.setHorizontalAlignment(JTextField.CENTER);
        txtCostoCompra.setHorizontalAlignment(JTextField.CENTER);
        txtBuscarProductosIn.setHorizontalAlignment(JTextField.CENTER);
        
        
        txtBuscador.addFocusListener(new FullSelectorListener());
        txtBuscarProductosIn.addFocusListener(new FullSelectorListener());
        txtCantidadCompra.addFocusListener(new FullSelectorListener());
        txtCostoCompra.addFocusListener(new FullSelectorListener());
        
        jButtonActualizar.setToolTipText("Actualizar Datos");
        jButtonAdicionar.setToolTipText("Agregar Datos");
        jButtonAtras.setToolTipText("Salir De La Ventana");
        jButtonEditarFila.setToolTipText("Editar");
        jButtonLimpiar.setToolTipText("Limpiar Datos");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DateFechaEntrada = new com.toedter.calendar.JDateChooser();
        txtBuscador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboProductos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtCantidadCompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCostoCompra = new javax.swing.JTextField();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableInventarionicial = new javax.swing.JTable();
        jButtonEditarFila = new javax.swing.JButton();
        txtBuscarProductosIn = new javax.swing.JTextField();
        jButtonAtras = new javax.swing.JButton();
        jlTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Buscar Productos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 14, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Fecha Entrada");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 14, -1, -1));
        jPanel1.add(DateFechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 37, 160, -1));
        jPanel1.add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 37, 122, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Productos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 14, 83, -1));

        comboProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductosActionPerformed(evt);
            }
        });
        jPanel1.add(comboProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 37, 220, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Cantidad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 57, -1, -1));
        jPanel1.add(txtCantidadCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 80, 81, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Costo Compra");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 57, -1, -1));
        jPanel1.add(txtCostoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 80, 107, -1));

        jButtonAdicionar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Adicionar.png"))); // NOI18N
        jButtonAdicionar.setText("Adicionar");
        jPanel1.add(jButtonAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 69, 118, -1));

        jButtonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar1.png"))); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jPanel1.add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 69, -1, 39));

        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar.png"))); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jPanel1.add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 610, 130));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        TableInventarionicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableInventarionicial);

        jButtonEditarFila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar tabla.png"))); // NOI18N
        jButtonEditarFila.setText("Editar");

        txtBuscarProductosIn.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar Productos En Inventario", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscarProductosIn, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditarFila)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBuscarProductosIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarFila))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 610, 220));

        jButtonAtras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regresar.png"))); // NOI18N
        jButtonAtras.setText("Regresar");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 130, -1));

        jlTitulo.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ventas Diarias.png"))); // NOI18N
        jlTitulo.setText("Inventario Inicial");
        getContentPane().add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void comboProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductosActionPerformed
        ComboMedicamento combo=(ComboMedicamento) comboProductos.getSelectedItem();
        txtCantidadCompra.setText("1");
        txtCostoCompra.setText(combo.getPrecioCompra());
    }//GEN-LAST:event_comboProductosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser DateFechaEntrada;
    public javax.swing.JTable TableInventarionicial;
    public javax.swing.JComboBox<String> comboProductos;
    public javax.swing.JButton jButtonActualizar;
    public javax.swing.JButton jButtonAdicionar;
    public javax.swing.JButton jButtonAtras;
    public javax.swing.JButton jButtonEditarFila;
    public javax.swing.JButton jButtonLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlTitulo;
    public javax.swing.JTextField txtBuscador;
    public javax.swing.JTextField txtBuscarProductosIn;
    public javax.swing.JTextField txtCantidadCompra;
    public javax.swing.JTextField txtCostoCompra;
    // End of variables declaration//GEN-END:variables
}
