/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.ActionControladorClientes;
import Controlador.ActionControladorCompras;
import Controlador.ActionControladorInventarioI;
import Controlador.ActionControladorLaboratorios;
import Controlador.ActionControladorMedicamentos;
import Controlador.ActionControladorProveedor;
import Controlador.ActionControladorVendedores;
import Controlador.ActionControladorVentaPeriodo;
import Controlador.ActionControladorVentas;
import Controlador.FocusControladorCompras;
import Controlador.KeyControladorCompras;
import Controlador.KeyControladorInventarioI;
import Controlador.KeyControladorVendedor;
import Controlador.KeyControladorVentas;
import Controlador.MouseControladorVentas;
import Modelo.OperacionesClientes;
import Modelo.OperacionesCompras;
import Modelo.OperacionesInventarioInicial;
import Modelo.OperacionesLaboratorios;
import Modelo.OperacionesMedicamentos;
import Modelo.OperacionesProveedores;
import Modelo.OperacionesVendedores;
import Modelo.OperacionesVentaPeriodo;
import Modelo.OperacionesVentas;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;

/**
 *
 * @author Aldair
 */
public class menu extends javax.swing.JFrame {
    Inicio inicio= new Inicio();
    
    public menu() {
        initComponents();
        this.setLocationRelativeTo(null);//centra el formulario
        this.setResizable(false);//desabilita el maximizar
        //--------------------------------------------------------------------
        //muestra la fecha y hora
        String fechahora;
        Calendar cal=Calendar.getInstance();
        fechahora=cal.get(Calendar.DATE)+"/"+cal.get(Calendar.MONTH)+"/"+cal.get(Calendar.YEAR)+"  "+cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+":"+cal.get(Calendar.SECOND);
        this.fechahora.setText(fechahora);
        //----------------------------------------------------------------------
        //Cerrar con tecla esc
        txtoculto.setVisible(false);
    }
    //metodo para cambiar el icono tasa de café de java
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/printlogo.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fechahora = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        txtoculto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMSalir = new javax.swing.JMenuItem();
        jMinimizar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmMedicamento = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmLaboratorio = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmVendedor = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmVentas = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();
        ReporteVentasDiarias = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        ReporteVentaPeriodo = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GENESIS CORP");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechahora.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        fechahora.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(fechahora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 180, 30));

        txtUsuario.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 600, 260, 30));
        getContentPane().add(txtoculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 40, 110, 20));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoempresa.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 650));

        jMenuBar2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar2.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jMenuBar2.setMargin(new java.awt.Insets(1, 1, 1, 1));

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jMenu3.setText("Inicio");
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        jMSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        jMSalir.setText("Cerrar Sesión");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMenu3.add(jMSalir);

        jMinimizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.ALT_MASK));
        jMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar.png"))); // NOI18N
        jMinimizar.setText("Minimizar");
        jMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinimizarActionPerformed(evt);
            }
        });
        jMenu3.add(jMinimizar);

        jMenuBar2.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        jMenu4.setText("Registrar");
        jMenu4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jmMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medicamento.png"))); // NOI18N
        jmMedicamento.setText("Registrar Medicamento");
        jmMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMedicamentoActionPerformed(evt);
            }
        });
        jMenu4.add(jmMedicamento);
        jMenu4.add(jSeparator1);

        jmLaboratorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laboratorio1.png"))); // NOI18N
        jmLaboratorio.setText("Registrar Laboratorio");
        jmLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLaboratorioActionPerformed(evt);
            }
        });
        jMenu4.add(jmLaboratorio);
        jMenu4.add(jSeparator2);

        jmVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedor1.png"))); // NOI18N
        jmVendedor.setText("Registrar Vendedor");
        jmVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVendedorActionPerformed(evt);
            }
        });
        jMenu4.add(jmVendedor);
        jMenu4.add(jSeparator3);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        jMenuItem1.setText("Registrar Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);
        jMenu4.add(jSeparator8);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proveedor.png"))); // NOI18N
        jMenuItem3.setText("Registrar Proveedores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar2.add(jMenu4);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/generar.png"))); // NOI18N
        jMenu1.setText("Generar");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jmVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas.png"))); // NOI18N
        jmVentas.setText("Dispensación De Medicamentos");
        jmVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVentasActionPerformed(evt);
            }
        });
        jMenu1.add(jmVentas);
        jMenu1.add(jSeparator4);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compra.png"))); // NOI18N
        jMenuItem2.setText("Acta De Recepción Técnica");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/InventarioInicial.png"))); // NOI18N
        jMenuItem6.setText("Inventario Inicial");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator9);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        jMenu7.setText("Reportes");

        ReporteVentasDiarias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ventas Diarias.png"))); // NOI18N
        ReporteVentasDiarias.setText("Reportes Ventas Diarias");
        ReporteVentasDiarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteVentasDiariasActionPerformed(evt);
            }
        });
        jMenu7.add(ReporteVentasDiarias);
        jMenu7.add(jSeparator11);

        ReporteVentaPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ventas Diarias.png"))); // NOI18N
        ReporteVentaPeriodo.setText("Reporte De Ventas Por Periodos");
        ReporteVentaPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteVentaPeriodoActionPerformed(evt);
            }
        });
        jMenu7.add(ReporteVentaPeriodo);
        jMenu7.add(jSeparator10);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compras diarias.png"))); // NOI18N
        jMenuItem5.setText("Acta De Recepción ");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);
        jMenu7.add(jSeparator7);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventarios.png"))); // NOI18N
        jMenuItem4.setText("Inventario");
        jMenu7.add(jMenuItem4);

        jMenu1.add(jMenu7);

        jMenuBar2.add(jMenu1);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contactos.png"))); // NOI18N
        jMenu5.setText("Contáctanos");
        jMenu5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contacto1.png"))); // NOI18N
        jMenuItem7.setText("información");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar2.add(jMenu5);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimiento.png"))); // NOI18N
        jMenu2.setText("Mantenimiento");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimeinto.png"))); // NOI18N
        jMenu9.setText("Configuraciones");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medicamento.png"))); // NOI18N
        jMenuItem9.setText("Medicamento");
        jMenu9.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laboratorio1.png"))); // NOI18N
        jMenuItem10.setText("Laboratorios");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedor1.png"))); // NOI18N
        jMenuItem11.setText("Vendedores");
        jMenu9.add(jMenuItem11);

        jMenu2.add(jMenu9);

        jMenuBar2.add(jMenu2);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultante.png"))); // NOI18N
        jMenu8.setText("Consultas");
        jMenu8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuBar2.add(jMenu8);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ayuda.png"))); // NOI18N
        jMenu6.setText("Ayuda");
        jMenu6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ayuda1.png"))); // NOI18N
        jMenuItem8.setText("uso del sistema");
        jMenu6.add(jMenuItem8);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jmVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVendedorActionPerformed
        vendedores ven=new vendedores();
        OperacionesVendedores operaciones=new OperacionesVendedores();
        ActionControladorVendedores Contro=new ActionControladorVendedores(ven,operaciones);
        KeyControladorVendedor key=new KeyControladorVendedor(ven);
        ven.setVisible(true);
    }//GEN-LAST:event_jmVendedorActionPerformed

    private void jmLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLaboratorioActionPerformed
        laboratorios lab= new laboratorios();
        OperacionesLaboratorios operaciones=new OperacionesLaboratorios();
        ActionControladorLaboratorios contro=new ActionControladorLaboratorios(lab,operaciones);
        lab.setVisible(true);
    }//GEN-LAST:event_jmLaboratorioActionPerformed

    private void jmMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMedicamentoActionPerformed
        medicamentos vtMedicamento=new medicamentos();
        OperacionesMedicamentos operaciones=new OperacionesMedicamentos();
        ActionControladorMedicamentos controlador= new ActionControladorMedicamentos(vtMedicamento,operaciones);
        vtMedicamento.setVisible(true);
    }//GEN-LAST:event_jmMedicamentoActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        dispose();
        Inicio inicio= new Inicio();
        inicio.setVisible(true);
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinimizarActionPerformed
         this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jMinimizarActionPerformed

    private void jmVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVentasActionPerformed
        Ventas ven= new Ventas();
        int cedula=Integer.parseInt(txtoculto.getText());
        OperacionesVentas operaciones=new OperacionesVentas();
        ActionControladorVentas controladorAction=new ActionControladorVentas(ven,operaciones,cedula);
        MouseControladorVentas controladorMouse=new MouseControladorVentas(ven);
        KeyControladorVentas controladorKey=new KeyControladorVentas(ven,operaciones);
        ven.setVisible(true);
    }//GEN-LAST:event_jmVentasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Clientes vistaCliente=new Clientes();
        OperacionesClientes operaciones=new OperacionesClientes();
        ActionControladorClientes controlador= new ActionControladorClientes(vistaCliente,operaciones);
        vistaCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void ReporteVentasDiariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteVentasDiariasActionPerformed
        ReporteVentasDiarias vtnreporte=new ReporteVentasDiarias();
        this.jLabel1.add(vtnreporte);
        vtnreporte.setLocation(600, 30);
        vtnreporte.show();
    }//GEN-LAST:event_ReporteVentasDiariasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Compras compra=new Compras();
        OperacionesCompras operaciones=new OperacionesCompras();
        ActionControladorCompras Action=new ActionControladorCompras(compra,operaciones);
        KeyControladorCompras Key=new KeyControladorCompras(compra,operaciones);
        FocusControladorCompras focus=new FocusControladorCompras(compra,operaciones);
        compra.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        InventarioInicial InventarioI=new InventarioInicial();
        this.jLabel1.add(InventarioI);
        InventarioI.setLocation(400, 60);
        OperacionesInventarioInicial operacion=new OperacionesInventarioInicial();
        ActionControladorInventarioI actiom = new ActionControladorInventarioI(InventarioI,operacion);
        KeyControladorInventarioI key = new KeyControladorInventarioI(InventarioI,operacion);
        InventarioI.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Proveedores vtProveedor=new Proveedores();
        OperacionesProveedores operaciones=new OperacionesProveedores();
        this.jLabel1.add(vtProveedor);
        vtProveedor.setLocation(400, 60);
        ActionControladorProveedor contro=new ActionControladorProveedor(vtProveedor,operaciones);
        vtProveedor.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void ReporteVentaPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteVentaPeriodoActionPerformed
        ReporteVentasPorPeriodo vtPeriodo=new ReporteVentasPorPeriodo();
        OperacionesVentaPeriodo operaciones=new OperacionesVentaPeriodo();
        this.jLabel1.add(vtPeriodo);
        vtPeriodo.setLocation(400, 60);
        ActionControladorVentaPeriodo contro=new ActionControladorVentaPeriodo(vtPeriodo,operaciones);
        vtPeriodo.setVisible(true);
    }//GEN-LAST:event_ReporteVentaPeriodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ReporteVentaPeriodo;
    private javax.swing.JMenuItem ReporteVentasDiarias;
    private javax.swing.JLabel fechahora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMinimizar;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem jmLaboratorio;
    private javax.swing.JMenuItem jmMedicamento;
    private javax.swing.JMenuItem jmVendedor;
    private javax.swing.JMenuItem jmVentas;
    public javax.swing.JLabel txtUsuario;
    public javax.swing.JLabel txtoculto;
    // End of variables declaration//GEN-END:variables

}
