/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Aldair
 */
public class ReporteVentasPorPeriodo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteVentasPorPeriodo
     */
    public ReporteVentasPorPeriodo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdtFechaFinal = new com.toedter.calendar.JDateChooser();
        jdtFechaInicial = new com.toedter.calendar.JDateChooser();
        jButtonGenerarReporte = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdtFechaFinal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)), "Fecha Final Venta", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        getContentPane().add(jdtFechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, 50));

        jdtFechaInicial.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)), "Fecha Incial Venta", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        getContentPane().add(jdtFechaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 210, 50));

        jButtonGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ventas Diarias.png"))); // NOI18N
        jButtonGenerarReporte.setText("Generar");
        getContentPane().add(jButtonGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 110, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Digite Las Fechas Para Generar El Reporte");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonGenerarReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public com.toedter.calendar.JDateChooser jdtFechaFinal;
    public com.toedter.calendar.JDateChooser jdtFechaInicial;
    // End of variables declaration//GEN-END:variables
}
