/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.util;
import Modelo.conectorBD;
import Reportes.AstractJasperReport;
import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.Date;

/**
 *
 * @author Aldair
 */
public class ReporteVentasDiarias extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteVentasDiarias
     */
    public ReporteVentasDiarias() {
        initComponents();
        KeyboardFocusManager kb=KeyboardFocusManager.getCurrentKeyboardFocusManager();
        kb.addKeyEventPostProcessor(new KeyEventPostProcessor(){
            public boolean postProcessKeyEvent(KeyEvent e){
                if(e.getKeyCode()==KeyEvent.VK_ESCAPE){
                    dispose();
                    return true;
                }
                return false;
            }
        });
        this.jdFecha.setDate(new Date());
        jButtonGenerarReporte.setToolTipText("Generar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdFecha = new com.toedter.calendar.JDateChooser();
        jButtonGenerarReporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Fecha Ventas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 102))); // NOI18N
        getContentPane().add(jdFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 180, 50));

        jButtonGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ventas Diarias.png"))); // NOI18N
        jButtonGenerarReporte.setText("Generar");
        jButtonGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 164));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarReporteActionPerformed
        String fechaventa=util.aFechaMYSQL(jdFecha.getDate());
        generarReporte(fechaventa);
        AstractJasperReport.ejecutarReporte();
    }//GEN-LAST:event_jButtonGenerarReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerarReporte;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JDateChooser jdFecha;
    // End of variables declaration//GEN-END:variables
private final conectorBD conector= new conectorBD();
private void generarReporte(String fecha){
       try{
          if(conector.conectar()){
              AstractJasperReport.creaReporteVentaDiaria(conector.getconecction(),"C:\\Users\\dehoy\\OneDrive\\Documentos\\NetBeansProjects\\farmacia\\src\\Reportes\\VentasDiarias.jasper",fecha);
          }else{
              System.out.print("Error Al Conectarse Con BD");
          } 
       }catch(Exception e){
         System.out.println("Error...");
         System.err.println(e.getMessage());
       }
    }
}
